### ISSUE TITLE
Problem adding Debian to pakiti-server VDS

### ISSUE THREAD

**Issue by anti-moi** [CESNET/pakiti-server#144]
Hello,

I'm trying to install pakiti-server, everything seems to work except when adding Debian VDS, svn://anonscm.debian.org/svn/secure-testing/data/DSA/ doesn't work 
```
svn: E000101: Unable to connect to a repository at URL 'svn://anonscm.debian.org/svn/secure-testing/data/DSA'
svn: E000101: Can't connect to host 'anonscm.debian.org': Network is unreachable
```
I have also seen that some oval security seems to be available : https://www.debian.org/security/oval/ 

Can you please tell me how to add Debian to pakiti?

Thank you

**Comment by kouril** [comment]
On Mon, Jul 30, 2018 at 04:30:20AM -0700, anti-moi wrote:
> I'm trying to install pakiti-server, everything seems to work except when adding Debian VDS, svn://anonscm.debian.org/svn/secure-testing/data/DSA/ doesn't work 
> ```
> svn: E000101: Unable to connect to a repository at URL 'svn://anonscm.debian.org/svn/secure-testing/data/DSA'
> svn: E000101: Can't connect to host 'anonscm.debian.org': Network is unreachable
> ```
> I have also seen that some oval security seems to be available : https://www.debian.org/security/oval/ 
> 
> Can you please tell me how to add Debian to pakiti?

We had to remove the SVN-based method of getting information on
packages (since it's not supported anymore) and switched to http-based
transport. Please try using
https://salsa.debian.org/security-tracker-team/security-tracker/raw/master/data/DSA/list
as the URI instead of the svn:// one.

As for OVAL for Debian - it wasn't working when I looked a few months
back, we'd need to evaluate if it's better now.

Daniel

**Comment by anti-moi** [comment]
It seems to work, thank you, and thank you for the fast answer
